WITH cte AS(
    SELECT
        DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
    FROM HR_EMPLOYEES e
    GROUP BY DEPT_ID
)
SELECT cte.DEPT_ID, d.DEPT_NAME_EN, cte.AVG_SAL
FROM cte
LEFT JOIN HR_DEPARTMENT d ON cte.DEPT_ID = d.DEPT_ID
ORDER BY AVG_SAL DESC