SELECT
    p.PRODUCT_CODE,
    COALESCE(SUM(p.PRICE * s.SALES_AMOUNT),0) AS SALES
FROM PRODUCT p
LEFT JOIN OFFLINE_SALE s ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC