-- GROUP BY를 통해, 여러개의 집계를 한번에 처리할 수 있다. HAVING절의 집계도 가능하다

SELECT
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(COALESCE(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE, FISH_COUNT, MAX_LENGTH