WITH RECURSIVE cte AS(
    SELECT 0 AS HOUR

    UNION ALL

    SELECT HOUR +1 AS HOUR FROM cte WHERE HOUR < 23
)
SELECT cte.HOUR, COUNT(ANIMAL_OUTS.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
RIGHT JOIN cte ON cte.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY cte.HOUR
