# SELECT a.FISH_TYPE, MAX(a.LENGTH)
# FROM FISH_INFO a
# JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
# GROUP BY a.FISH_TYPE;


WITH cte AS(
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)
SELECT a.ID, b.FISH_NAME, cte.MAX_LENGTH AS LENGTH
FROM cte
JOIN FISH_INFO a ON a.FISH_TYPE = cte.FISH_TYPE AND a.LENGTH = cte.MAX_LENGTH
JOIN FISH_NAME_INFO b WHERE b.FISH_TYPE = cte.FISH_TYPE
ORDER BY ID;