-- 복습
-- SELECT 절에서 GROUP BY에 포함되지 않은 컬럼은 반드시 집계 함수(예: MAX(), MIN(), COUNT(), SUM() 등)를 통해서만 포함 가능
-- 아래는 틀린 풀이
-- SELECT ID, FISH_TYPE, MAX(LENGTH)
-- FROM FISH_INFO
-- GROUP BY FISH_TYPE

-- 정답 1
WITH cte AS(
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)
SELECT a.ID, b.FISH_NAME, cte.MAX_LENGTH AS LENGTH
FROM cte
JOIN FISH_INFO a ON a.FISH_TYPE = cte.FISH_TYPE AND a.LENGTH = cte.MAX_LENGTH
JOIN FISH_NAME_INFO b ON b.FISH_TYPE = cte.FISH_TYPE
ORDER BY ID;


-- 정답 2
SELECT a.ID, b.FISH_NAME, max_length.LENGTH
FROM FISH_INFO a
JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) as max_length
ON max_length.FISH_TYPE = a.FISH_TYPE
AND max_length.LENGTH = a.LENGTH
ORDER BY a.ID
