SELECT
    info.INGREDIENT_TYPE,
    SUM(shipment.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF shipment
JOIN ICECREAM_INFO info ON shipment.FLAVOR = info.FLAVOR
GROUP BY info.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER